name: jpx-frde

channels:
  - conda-forge

dependencies:
  - ipython
  - ipykernel
  - python
  - numpy
  - matplotlib
  - pandas
  - altair
  - beautifulsoup4
  - pre-commit
  - pip
  - pip:
    - -r requirements.txt
